### ISSUE TITLE
coordinate values is partly different between keypoints file and Descriptor file

### ISSUE THREAD

**Issue by junqiangchen** [bbrister/SIFT3D#22]
hi,
i run the example featureC.c code,and generate the keypoints file and Descriptor file.both of all contain feature point coordinate,but i find the coordinate values is partly different between those files,there have 454 feature points,1-382  coordinate values are same,but 383-454 coordinate values are different.

**Comment by bbrister** [comment]
Hello,

Thanks for your interest. 

You are probably seeing different coordinates for features which are in higher octaves of the image pyramid. Descriptor coordinates refer to the original image space, whereas keypoint coordinates refer to the image pyramid level in which they are detected. To do this conversion, multiply the keypoint coordinate by 2 ^ (octave index). Does this match with what you're seeing?

**Comment by junqiangchen** [comment]
thank you bbrister,this is right.
