### ISSUE TITLE
Do you have the code to compile in Python?

### ISSUE THREAD

**Issue by gledsonmelotti** [bbrister/SIFT3D#24]
Hello @bbrister.
Congratulations on the codes. He's very interesting.
Is there any way to compile such code in Python?

Best regards,
Gledson

**Comment by bbrister** [comment]
Hello, thanks for your interest. I have an experimental [python](https://github.com/bbrister/SIFT3D/tree/python/wrappers/python) branch which does this for the I/O routines. It is not necessary to recompile the code, it is only necessary to call the shared libraries using the ctypes module in Python. However, it is often more convenient to write a short wrapper library in C to simplify the use of ctypes. I have already done this for the I/O routines. It would be great if someone could extend it to cover other functions as well.

**Comment by gledsonmelotti** [comment]
Hello Blaine Rister, I'm sorry for the inconvenience. I am a beginner in
classification and python studies. I never studied "C".

Best regards,
Gledson.

Em seg., 6 de jul. de 2020 às 23:44, Blaine Rister <notifications@github.com>
escreveu:
