### ISSUE TITLE
Accurate keypoint localization

### ISSUE THREAD

**Issue by ufukefe** [bbrister/SIFT3D#27]
Hi, thanks for your excellent work and for sharing it!

I am using your algorithm on Matlab and it is working pretty well.

I am wondering that do you use 'Accurate keypoint localization' that is mentioned on the [SIFT 2004](https://people.eecs.berkeley.edu/~malik/cs294/lowe-ijcv04.pdf) paper, or do you assign at
the location and scale of the central sample point just like in the [SIFT 1999](https://ieeexplore.ieee.org/document/790410) paper?

**Comment by bbrister** [comment]
Hello, thanks for your interest. I am glad that you find the software useful.

If I recall correctly, we experimented with sub-pixel localization, but we weren't able to achieve satisfactory results, so it is currently disabled. That might be a way to improve the results.

**Comment by ufukefe** [comment]
Thank you for your answer!
